### ISSUE TITLE
Payment issue

### ISSUE THREAD

**Issue by peteruithoven** [elly-code/cherrypick#3]
### What happened?

I tried paying for Picker, but that's failing. Looking at the logs from AppCenter I'm getting:
``` json
{
  "errors": [
    {
      "code": "StripeInvalidRequestError",
      "title": "Error",
      "detail": "As per Indian regulations, only registered Indian businesses (i.e. sole proprietorships, limited liability partnerships and companies, but not individuals) can accept international payments. More info here: https://stripe.com/docs/india-exports"
    }
  ]
}
```

### Screenshots

![Screenshot from 2022-06-10 11-55-05@2x](https://user-images.githubusercontent.com/523210/173041609-1a74e724-de5f-4f9f-920c-657015ad2298.png)

### OS name and version

elementary OS 6.1 Jólnir

### Version

-

**Comment by adithyankv** [comment]
Oh. Seems like an issue with how I've configured stripe. I'll look into it. Thank you for pointing it out.

**Comment by adithyankv** [comment]
Yeah this is an issue with how I've set up my stripe account. Regulatory issue with stripe concerning individual accounts as opposed to business one. Will probably take some time to fix, so in the mean time I'll probably just remove the payment option from appcenter.

**Comment by adithyankv** [comment]
I have temporarily removed the payment option from the appcenter. Should fix the issue for now until I can sort out the actual stripe payment issue. In the mean time if you'd still like to donate you can perhaps try  using

[![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/X8X7D99T6)

**Comment by peteruithoven** [comment]
Seems to work :+1:
